# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 603)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Top controls
        self.comboAccounts = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboAccounts.setGeometry(QtCore.QRect(20, 40, 150, 26))
        self.comboAccounts.setObjectName("comboAccounts")

        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 150, 20))
        self.label.setObjectName("label")

        self.labelBalanceText = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelBalanceText.setGeometry(QtCore.QRect(200, 10, 120, 20))
        self.labelBalanceText.setObjectName("labelBalanceText")

        self.labelBalanceValue = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelBalanceValue.setGeometry(QtCore.QRect(200, 40, 120, 20))
        self.labelBalanceValue.setObjectName("labelBalanceValue")

        self.labelAccountType = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelAccountType.setGeometry(QtCore.QRect(20, 70, 150, 20))
        self.labelAccountType.setObjectName("labelAccountType")

        # Left group box (Create account) - aligned grid-like spacing
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 110, 260, 220))
        self.groupBox.setObjectName("groupBox")

        self.labelNewName = QtWidgets.QLabel(parent=self.groupBox)
        self.labelNewName.setGeometry(QtCore.QRect(10, 20, 100, 16))
        self.labelNewName.setObjectName("labelNewName")
        self.labelNewName.setText("New Name:")

        self.editNewName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.editNewName.setGeometry(QtCore.QRect(10, 40, 240, 24))
        self.editNewName.setObjectName("editNewName")

        self.labelInitialBalance = QtWidgets.QLabel(parent=self.groupBox)
        self.labelInitialBalance.setGeometry(QtCore.QRect(10, 74, 120, 16))
        self.labelInitialBalance.setObjectName("labelInitialBalance")
        self.labelInitialBalance.setText("Initial Balance:")

        self.editInitialBalance = QtWidgets.QLineEdit(parent=self.groupBox)
        self.editInitialBalance.setGeometry(QtCore.QRect(10, 94, 240, 24))
        self.editInitialBalance.setObjectName("editInitialBalance")

        self.radioRegular = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioRegular.setGeometry(QtCore.QRect(10, 130, 120, 24))
        self.radioRegular.setObjectName("radioRegular")

        self.radioSavings = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioSavings.setGeometry(QtCore.QRect(140, 130, 120, 24))
        self.radioSavings.setObjectName("radioSavings")

        self.buttonCreateAccount = QtWidgets.QPushButton(parent=self.groupBox)
        self.buttonCreateAccount.setGeometry(QtCore.QRect(80, 170, 100, 28))
        self.buttonCreateAccount.setObjectName("buttonCreateAccount")

        # Right group box (Deposit/Withdraw)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 110, 300, 260))
        self.groupBox_2.setObjectName("groupBox_2")

        self.labelAmountNote = QtWidgets.QLabel(parent=self.groupBox_2)
        self.labelAmountNote.setGeometry(QtCore.QRect(10, 20, 280, 20))
        self.labelAmountNote.setObjectName("labelAmountNote")
        self.labelAmountNote.setText("Enter amount:")

        self.editAmount = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.editAmount.setGeometry(QtCore.QRect(10, 46, 280, 28))
        self.editAmount.setObjectName("editAmount")

        self.buttonDeposit = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.buttonDeposit.setGeometry(QtCore.QRect(100, 90, 100, 28))
        self.buttonDeposit.setObjectName("buttonDeposit")

        self.buttonWithdraw = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.buttonWithdraw.setGeometry(QtCore.QRect(100, 134, 100, 28))
        self.buttonWithdraw.setObjectName("buttonWithdraw")

        # Status label anchored near bottom, spans width
        self.labelStatus = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelStatus.setGeometry(QtCore.QRect(20, 560, 760, 30))
        self.labelStatus.setObjectName("labelStatus")
        self.labelStatus.setWordWrap(True)
        self.labelStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        self.labelStatus.setSizePolicy(sizePolicy)
        self.labelStatus.setMinimumHeight(20)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Select account:"))
        self.labelBalanceText.setText(_translate("MainWindow", "Balance:"))
        self.labelBalanceValue.setText(_translate("MainWindow", "TextLabel"))
        self.labelAccountType.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.radioRegular.setText(_translate("MainWindow", "Regular"))
        self.radioSavings.setText(_translate("MainWindow", "Savings"))
        self.buttonCreateAccount.setText(_translate("MainWindow", "Create Account"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.buttonDeposit.setText(_translate("MainWindow", "Deposit"))
        self.buttonWithdraw.setText(_translate("MainWindow", "Withdraw"))
        self.labelStatus.setText(_translate("MainWindow", "TextLabel"))
